// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace emarket.Migrations
{
    [DbContext(typeof(EMarketDbContext))]
    [Migration("20240610110654_orders")]
    partial class orders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("emarket.Models.ItemViewModel", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("emarket.Models.OrderItemModel", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PurchasedAmount")
                        .HasColumnType("int");

                    b.Property<string>("PurchasedItem")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrderId");

                    b.HasIndex("PurchasedItem");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("emarket.Models.OrderUserModel", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PurchaserUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("totalPrice")
                        .HasColumnType("float");

                    b.HasKey("OrderId");

                    b.HasIndex("PurchaserUsername");

                    b.ToTable("OrderUsers");
                });

            modelBuilder.Entity("emarket.Models.UserViewModel", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("emarket.Models.OrderItemModel", b =>
                {
                    b.HasOne("emarket.Models.ItemViewModel", "Purchased")
                        .WithMany()
                        .HasForeignKey("PurchasedItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Purchased");
                });

            modelBuilder.Entity("emarket.Models.OrderUserModel", b =>
                {
                    b.HasOne("emarket.Models.UserViewModel", "Purchaser")
                        .WithMany()
                        .HasForeignKey("PurchaserUsername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Purchaser");
                });
#pragma warning restore 612, 618
        }
    }
}
